version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-lambda-dynamo-third"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1q0i5rbgklcan"
s3_prefix = "sam-lambda-dynamo-third"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
